# Generated by Django 4.2.7 on 2023-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='student',
            name='conclusao',
            field=models.CharField(choices=[('TCC', 'TCC'), ('Estágio', 'Estágio'), ('TCC e estágio', 'TCC e estágio'), ('Não decidiu', 'Não decidiu')], default=('Não decidiu', 'Não decidiu'), max_length=13),
        ),
        migrations.AddField(
            model_name='student',
            name='curso',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='serie',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
