# Generated by Django 4.2.7 on 2023-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0002_rename_name_student_nome_student_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(default='', max_length=11),
        ),
    ]
